### PR TITLE
[KO-349] Added config schema for aerospike server 7.2

### PR DESCRIPTION
**Pull request by sud82**

### CODE REVIEW

**Review by dwelch-spike — CHANGES_REQUESTED** [review]
I have a few questions.

1. Why did the default node ID change? (for  my understanding)
2. Are you sure that `restrict-version-skipping` and `skip-versions-within` are dynamic? I don't see them being handles in the info changes here https://github.com/citrusleaf/aerospike-server/compare/7.1.0.5...7.2.0.0-rc1

**Comment by sud82** [comment]
@dwelch-spike 
1. This may be due to the way schema is generated. Take the default node ID of the node where schema generation runs. (This can be reverted)
2. As per docs, they are dynamic https://github.com/citrusleaf/aerospike-websites/pull/1164/files. I'll confirm with the server team.

**Comment by dwelch-spike** [comment]
@sud82 I'm not sure what the right move is for the default node id. Does it even make sense to have one? Maybe it should be blank.

**Review by dwelch-spike — APPROVED** [review]
LGTM. @sud82 My vote is that the default node id should be empty. Once you decide, I think this can be merged.

**Comment by a-spiker** [comment]
Changes: 
- Removed `evict-sys-memory-pct` from 7.1 schema
- `node-id.default` value is set as empty for 7.2 schema

**Pull request merged**
